steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/photo-portfolio', '.']
  secretEnv: ['DB_URL', 'DB_USERNAME', 'DB_PASSWORD', 'GCS_KEY', 'PROJECT_ID', 'BUCKET']

deploy:
  step: 'Deploy'
  args: ['gcloud', 'run', 'deploy', 'photo-portfolio', '--image', 'gcr.io/$PROJECT_ID/photo-portfolio', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

environments:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_URL/versions/latest
      env: 'DB_URL'
    - versionName: projects/$PROJECT_ID/secrets/DB_USERNAME/versions/latest
      env: 'DB_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/GCS_KEY/versions/latest
      env: 'GCS_KEY'
    - versionName: projects/$PROJECT_ID/secrets/PROJECT_ID/versions/latest
      env: 'PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/BUCKET/versions/latest
      env: 'BUCKET'

images:
- 'gcr.io/$PROJECT_ID/photo-portfolio'
